apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeiisdevtest
  labels:
    app: sample
spec:
  replicas: 1
  template:
    metadata:
      name: kubeiisdevtest
      labels:
        app: sample
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: kubeiisdevtest
        image: mcr.microsoft.com/windows/servercore/iis:latest
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: sample
---
apiVersion: v1
kind: Service
metadata:
  name: kubeiisdevtest
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: sample